/* =========================================================
   BFlix — app.js
   طبقة البيانات المشتركة + منطق الصفحة الرئيسية وصفحة التفاصيل.
   البيانات مخزّنة في localStorage (نسخة Static بدون سيرفر).
   ========================================================= */

const STORAGE_KEY = "bflix_items";
const FAVORITES_KEY = "bflix_favorites";
const THEME_KEY = "bflix_theme";

/* ---------- بيانات تجريبية أولية (Seed) ---------- */
/* الصور هنا placeholder عامة (picsum.photos) — بدّلها من لوحة التحكم بصور حقيقية لديك. */
const SEED_ITEMS = [
  { id:"m1", type:"movie",  title:"ظلال المدينة",        year:2024, genre:"أكشن، جريمة",     rating:8.1, description:"محقق سابق يعود لملاحقة شبكة إجرامية سيطرت على أحياء المدينة القديمة، في سباق مع الزمن قبل أن تتكرر مأساة الماضي.", image:"https://picsum.photos/seed/bflix-m1/600/900", watchUrl:"https://example.com/watch/m1", featured:true,  addedAt:"2024-11-02" },
  { id:"m2", type:"movie",  title:"على حافة البحر",       year:2023, genre:"دراما، رومانسي",  rating:7.4, description:"قصة صيّاد يواجه خيارًا صعبًا بين حلمه القديم وعائلته الصغيرة في بلدة ساحلية هادئة.", image:"https://picsum.photos/seed/bflix-m2/600/900", watchUrl:"https://example.com/watch/m2", featured:false, addedAt:"2023-06-14" },
  { id:"m3", type:"movie",  title:"المدار السابع",        year:2025, genre:"خيال علمي، إثارة", rating:8.7, description:"طاقم محطة فضائية يكتشف إشارة غامضة تهدد بكشف حقيقة مهمتهم الحقيقية بعيدًا عن الأرض.", image:"https://picsum.photos/seed/bflix-m3/600/900", watchUrl:"https://example.com/watch/m3", featured:true,  addedAt:"2025-01-20" },
  { id:"m4", type:"movie",  title:"ضحكة أخيرة",           year:2022, genre:"كوميديا",         rating:6.9, description:"ثلاثة أصدقاء يخططون لحفلة مفاجئة تتحول إلى سلسلة من المواقف الكوميدية الكارثية.", image:"https://picsum.photos/seed/bflix-m4/600/900", watchUrl:"https://example.com/watch/m4", featured:false, addedAt:"2022-09-05" },
  { id:"m5", type:"movie",  title:"البيت رقم 12",         year:2024, genre:"رعب، غموض",       rating:7.2, description:"عائلة تنتقل إلى منزل قديم يخفي سرًا مظلمًا يعود لعقود من الزمن.", image:"https://picsum.photos/seed/bflix-m5/600/900", watchUrl:"https://example.com/watch/m5", featured:false, addedAt:"2024-03-18" },
  { id:"m6", type:"movie",  title:"سباق الوادي",          year:2021, genre:"مغامرة، أكشن",    rating:7.0, description:"فريق من المستكشفين يخوض رحلة محفوفة بالمخاطر عبر واد مجهول بحثًا عن كنز أسطوري.", image:"https://picsum.photos/seed/bflix-m6/600/900", watchUrl:"https://example.com/watch/m6", featured:false, addedAt:"2021-12-01" },
  { id:"m7", type:"movie",  title:"قهوة الصباح",          year:2025, genre:"دراما، كوميديا",  rating:7.8, description:"صاحبة مقهى صغير تعيد ترتيب حياتها بعد لقاء غيّر نظرتها للعالم من حولها.", image:"https://picsum.photos/seed/bflix-m7/600/900", watchUrl:"https://example.com/watch/m7", featured:false, addedAt:"2025-05-10" },
  { id:"m8", type:"movie",  title:"الحارس الأخير",        year:2020, genre:"أكشن، دراما",     rating:8.0, description:"حارس أمن متقاعد يجد نفسه مضطرًا للعودة لمهمة واحدة أخيرة لإنقاذ من يحب.", image:"https://picsum.photos/seed/bflix-m8/600/900", watchUrl:"https://example.com/watch/m8", featured:false, addedAt:"2020-08-22" },
  { id:"m9", type:"movie",  title:"رسائل لم تُرسل",        year:2023, genre:"دراما، رومانسي",  rating:8.3, description:"كاتبة تكتشف صندوقًا من الرسائل القديمة يقودها لإعادة اكتشاف قصة حب نسيها الزمن.", image:"https://picsum.photos/seed/bflix-m9/600/900", watchUrl:"https://example.com/watch/m9", featured:true,  addedAt:"2023-02-11" },
  { id:"m10", type:"movie", title:"خط النهاية",            year:2026, genre:"إثارة، جريمة",    rating:7.6, description:"صحفية استقصائية تلاحق فضيحة كبرى قد تكلفها حياتها إذا كشفت الحقيقة كاملة.", image:"https://picsum.photos/seed/bflix-m10/600/900", watchUrl:"https://example.com/watch/m10", featured:false, addedAt:"2026-02-01" },

  /* ---------- إضافات جديدة: أفلام أجنبية ---------- */
  { id:"m11", type:"movie", title:"Top Gun: Maverick",     year:2022, genre:"أكشن، دراما عسكرية", rating:8.3, description:"بعد أكثر من 30 عاماً من الخدمة كأحد أفضل الطيارين، يعود مافيغ (توم كروز) لتخطي الحدود واختبار طائرات جديدة، ليُطلب منه تدريب مجموعة من خريجي توپ غان النخبة لتنفيذ مهمة بالغة الخطورة ومستحيلة تقريباً. وهناك يضطر لمواجهة أشباح ماضيه ولقاء ابن صديقه الراحل غوس، لتشتعل المنافسة والمشاعر الإنسانية المؤثرة وسط مشاهد طيران حقيقية ومذهلة.", image:"https://i.postimg.cc/JhrKqdk1/MV5BMDBk-ZDNj-MWEt-OTdm-Mi00Nm-Ex-LTg5Mm-Mt-NTFl-YTJl-NWY5YTdm-Xk-Ey-Xk-Fqc-Gc-V1-FMjpg-UX1000.jpg", watchUrl:"https://a.qfilm.tv/watch.php?vid=ac9f157fe", featured:false, addedAt:"2026-03-01" },
  { id:"m12", type:"movie", title:"Mission: Impossible – Fallout", year:2018, genre:"أكشن، إثارة، تجسس، مغامرة", rating:7.7, description:"إذا كنت تحب أداء النجم توم كروز في Top Gun ومشاهد الأكشن الحقيقية التي تخطف الأنفاس، فهذا الفيلم يعتبر من قمة أفلام الأكشن الحديثة. تدور القصة حول العميل إيثان هانت وفريقه الذين يسابقون الزمن بعد أن فشلت مهمة لإنقاذ العالم، ليجدوا أنفسهم في مطاردات مجنونة، وقفزات مظلية مذهلة، ومشاهد أكشن تصويرية حقيقية بدون استخدام بدلاء، وكلها مليئة بالحماس والتشويق من البداية للنهاية.", image:"https://i.postimg.cc/8zqV8hGk/images-(2).jpg", watchUrl:"https://a.qfilm.tv/watch.php?vid=83f7c99e9", featured:false, addedAt:"2026-03-02" },
  { id:"m13", type:"movie", title:"Mad Max: Fury Road",    year:2015, genre:"أكشن، خيال علمي، مغامرة، إثارة", rating:8.1, description:"إذا كنت تبحث عن الأكشن المستمر، السرعة الجنونية، والمطاردات الأسطورية التي تجعلك على أطراف أصابعك، فهذا الفيلم هو الخيار الأمثل. تدور القصة في عالم مستقبلي صحراوي مقفر، حيث ينضم المحارب ماكس إلى الملكة فيوريوسا للهروب من طاغية يسيطر على مقدرات الحياة، في مطاردة سيارات ضخمة ومجنونة لا تنتهي أبداً وتعتمد على حركات تصويرية حقيقية ومؤثرات بصرية مبهرة تذكرك بروعة الأجواء الحماسية.", image:"https://i.postimg.cc/Ght0HMhL/images-(3).jpg", watchUrl:"https://a.qfilm.tv/watch.php?vid=87454c888", featured:false, addedAt:"2026-03-03" },

  { id:"s1", type:"series", title:"ما وراء الأفق",         year:2025, genre:"خيال علمي، إثارة", rating:8.5, description:"مجموعة من العلماء يفتحون بوابة بين الأبعاد، لتبدأ أحداث لا يمكن التنبؤ بعواقبها.", image:"https://picsum.photos/seed/bflix-s1/600/900", watchUrl:"https://example.com/watch/s1", featured:true,  addedAt:"2025-04-01" },
  { id:"s2", type:"series", title:"حي الأسرار",             year:2024, genre:"دراما، جريمة",    rating:8.0, description:"في حي شعبي هادئ ظاهريًا، تتكشف تدريجيًا شبكة من الأسرار العائلية المتشابكة.", image:"https://picsum.photos/seed/bflix-s2/600/900", watchUrl:"https://example.com/watch/s2", featured:false, addedAt:"2024-07-19" },
  { id:"s3", type:"series", title:"عرش الرمال",              year:2022, genre:"دراما تاريخية",  rating:8.9, description:"صراع على السلطة بين عائلتين متنافستين في مملكة صحراوية خلال حقبة مضطربة.", image:"https://picsum.photos/seed/bflix-s3/600/900", watchUrl:"https://example.com/watch/s3", featured:true,  addedAt:"2022-10-30" },
  { id:"s4", type:"series", title:"الوحدة 7",                year:2023, genre:"أكشن، إثارة",    rating:7.7, description:"فريق عمليات خاصة يخوض مهمات سرّية حول العالم، وكل حلقة تكشف طبقة جديدة من المؤامرة.", image:"https://picsum.photos/seed/bflix-s4/600/900", watchUrl:"https://example.com/watch/s4", featured:false, addedAt:"2023-11-08" },
  { id:"s5", type:"series", title:"ضحك بصوت عالٍ",            year:2021, genre:"كوميديا",        rating:7.1, description:"مجموعة أصدقاء يشاركوننا مواقف الحياة اليومية بأسلوب كوميدي خفيف ومحبب.", image:"https://picsum.photos/seed/bflix-s5/600/900", watchUrl:"https://example.com/watch/s5", featured:false, addedAt:"2021-05-17" },
  { id:"s6", type:"series", title:"نبض المدينة",              year:2026, genre:"دراما، رومانسي", rating:8.2, description:"أربع قصص متقاطعة لأشخاص تجمعهم مدينة واحدة وأقدار متشابكة عبر موسم كامل.", image:"https://picsum.photos/seed/bflix-s6/600/900", watchUrl:"https://example.com/watch/s6", featured:false, addedAt:"2026-01-15" },
  { id:"s7", type:"series", title:"الصمت الأبيض",             year:2024, genre:"رعب، غموض",      rating:7.5, description:"بلدة جبلية معزولة تشهد أحداثًا غامضة بعد عاصفة ثلجية استثنائية.", image:"https://picsum.photos/seed/bflix-s7/600/900", watchUrl:"https://example.com/watch/s7", featured:false, addedAt:"2024-12-09" },
  { id:"s8", type:"series", title:"ملف رقم 9",                year:2020, genre:"جريمة، إثارة",   rating:8.4, description:"محققة شابة تتولى قضايا باردة معقدة، وتكتشف أن بعضها مرتبط بماضيها الشخصي.", image:"https://picsum.photos/seed/bflix-s8/600/900", watchUrl:"https://example.com/watch/s8", featured:false, addedAt:"2020-03-27" },
];
